EduDuck/urls.py
#EduDuck/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles import views as static_views
from django.views.generic import TemplateView

import attachment.urls
import checkout.urls
import courses.urls
import homepage.views
import interaction.urls
import lesson.urls
import outcome.urls
import profile.urls
import support.urls
import terms.urls

urlpatterns =  [
    url(r'^$', homepage.views.home, name='homepage'),
#    url(r'^search/', include('haystack.urls')),
    url(r'^about/$', TemplateView.as_view(template_name = 'about.html')),
    url(r'^priced_items/', include(checkout.urls, namespace='checkout')),
    url(r'^support/', include(support.urls)),
    url(r'^terms/', include(terms.urls, namespace='terms')),
    url(r'^lesson/(?P<lesson_id>\d+)/lint/', include(outcome.urls)),
    url(r'^courses/', include(courses.urls)),
    url(r'^interaction/', include(interaction.urls)),
    url(r'^accounts/profile/', include(profile.urls)),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^attachment/', include(attachment.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

terms/urls.py
#terms/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from .import views

urlpatterns = [
    url(
        r'^$', 
        TemplateView.as_view(template_name='terms/terms_index.html'),
        name = 'terms_index'
    ),
    url(
        r'disclaimer/$',
        TemplateView.as_view(template_name='terms/terms_disclaimer.html'),
        name = 'terms_disclaimer'
    ),
    url(
        r'privacy/$',
        TemplateView.as_view(template_name='terms/terms_privacy.html'),
        name = 'terms_privacy'
    ),
    url(
        r'browsing/$', 
        TemplateView.as_view(template_name='terms/terms_browsing.html'),
        name = 'terms_browsing'
    ),
    url(
        r'enrolling/$', 
        TemplateView.as_view(template_name='terms/terms_enrolling.html'),
        name = 'terms_enrolling'
    ),
    url(
        r'creating/$',
        TemplateView.as_view(template_name='terms/terms_creating.html'),
        name = 'terms_creating'
    ),
]

terms/views.py
from django.shortcuts import render

# Create your views here.

terms/templates/terms/terms_base.html
{% extends "base.html" %}
{% load staticfiles %}

terms/templates/terms/terms_browsing.html
{% extends "terms/terms_base.html" %}

{% block breadcrumb %}
<p id='id_breadcrumb'>
    <a href="{% url 'terms:terms_index' %}">T&amp;C</a> &gt; 
    <a href="{% url 'terms:terms_browsing' %}">Browsing</a>
</p>
{% endblock breadcrumb %}

{% block contentheading %}
    <h2 id='id_page_title'>Terms and Conditions for Browsing the Website</h2>
{% endblock contentheading %}

{% block content %}
<p>Welcome to EduDuck.com. If you continue to browse and use this website, you are agreeing to comply with and be bound by the following terms and conditions of use, which together with our privacy policy govern EduDuck.com's relationship with you in relation to this website. If you disagree with any part of these terms and conditions, please consider letting us know of your objection using our <a href="{% url 'support' %}">support form</a> and in the meantime, please do not use our website.</p>

<p>This document covers the terms and condition for browsing EduDuck.com. Please note that should you enrol on a course, or decide to create a course, there are additional terms and conditions documents relating to those activities.</p>
<p>The use of this website is subject to the following terms of use:
<ol>
<li>The content of the pages of this website is for your general information and use only. It is subject to change without notice.</li>
<li>This website uses cookies to monitor browsing preferences. If you do allow cookies to be used, the following personal information may be stored by us for use by third parties: information facilitating logging in to the EduDuck.com website using third party authentication frameworks such as those provided by Facebook.com, Twitter.com or Google.com.</li>
<li>Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials found or offered on this website for any particular purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.</li>
<li>Your use of any information or materials on this website is entirely at your own risk, for which we shall not be liable. It shall be your own responsibility to ensure that any products, services or information available through this website meet your specific requirements.</li>
<li>Some of the material contained on this website is owned by or licensed to us. This material includes, but is not limited to, the design, layout, look, appearance and graphics. Reproduction is prohibited other than in accordance with the copyright notice, which is to be found in the footer of most pages on the website.</li>
<li>Some of the material contained on this website will be owned and/or created by third parties. A typical example would be courses created by other users of the website. The copyright on such material may be held by the third party and reproduction of such material would be subject to the consent and licence of the relevant copyright holder. The onus is on you to establish whether or not you are permitted by such third parties to make copies of their material.</li>
<li>All trade marks reproduced in this website which are not the property of, or licensed to, the operator are acknowledged on the website.</li>
<li>Unauthorised use of this website may give rise to a claim for damages and/or be a criminal offence.</li>
<li>Pages and resources on this website are likely to include links to other websites. These links are provided for your convenience to provide further information. They do not signify that we endorse the websites. We have no responsibility for the content of the linked websites.</li>
<li>Your use of this website and any dispute arising out of such use of the website is subject to the laws of Scotland.</li>
</ol>
</p>
{% endblock content %}

terms/templates/terms/terms_creating.html
{% extends "terms/terms_base.html" %}

{% block breadcrumb %}
<p id='id_breadcrumb'>
    <a href="{% url 'terms:terms_index' %}">T&amp;C</a> &gt; 
    <a href="{% url 'terms:terms_creating' %}">Creating</a>
</p>
{% endblock breadcrumb %}

{% block contentheading %}
    <h2 id='id_page_title'>Terms and Conditions for Creating Content</h2>
{% endblock contentheading %}

{% block content %}
<p>Thank you for your interest in creating a course on EduDuck.com.</p>
<p>In addition to the <a href="{% url 'terms:terms_browsing' %}">basic terms and conditions</a>, the following additional terms will apply should you choose to create a course.</p>
<ol>
    <li>Fee Structure. There is no charge to you for creating and uploading course material. You may charge your users for a course you have created. EduDuck.com will take a five percent fee for each user enrolment. If the course is free to users, there will clearly be no fee due to EduDuck.com.</li>
    <li>Arrangements will be made to transfer the balance of course fees, less our five percent and less the Stripe.com processing fee per transaction to a bank account nominated by you. <em>Details on this mechanism are yet to be finalised.</em></li> 
    <li>Appropriate nature of content. <em>Any offensive, abusive, hateful, or nonsensical courses or course material can be removed by EduDuck.com without warning to you</em>. Such material is outside of our terms and conditions and has no place on this site please.</li>
    <li>Please ensure that you are either the originator of any material which you post as part of your course, or if not, please ensure that such material is licenced for publication and redistribution on this site.</li>
    <li>Should you publish material for which you do not hold copyright or have a suitable licence to redistribute, you will assume any liabilities resulting from you publishing it on your course. EduDuck.com will not accept responsibility or liability for material you publish without appropriate licences.</li>
    <li>Plagiarism. Plagiarism will not be tolerated. To be clear, you may use work produced by others (given suitable licence as described above), provided that you give credit to the original author(s). Categorically, you must not pass off work by others as your own. Should EduDuck.com become aware of plagiarised material you may be asked to either remove, replace or give proper credit to the originating author. Failure to do so with a brief timescale may result in the suspension of the relevant course, or of your user account.</li>
    <li>Should EduDuck.com have to remove any courses or material due to any reason, even where this might limit the efficacy of courses and materials you have uploaded to the site, you understand that EduDuck.com will not reimburse you for any time spent preparing, producing and uploading those materials, nor will EduDuck.com reimburse you for lost enrolment fees from prospective users.</li>
</ol>
{% endblock content %}

terms/templates/terms/terms_disclaimer.html
{% extends "terms/terms_base.html" %}

{% block breadcrumb %}
<p id='id_breadcrumb'>
    <a href="{% url 'terms:terms_index' %}">T&amp;C</a> &gt; 
    <a href="{% url 'terms:terms_disclaimer' %}">Disclaimer</a>
</p>
{% endblock breadcrumb %}

{% block contentheading %}
    <h2 id='id_page_title'>Website Disclaimer</h2>
{% endblock contentheading %}

{% block content %}
<ol>
<li>
The information contained in this website is for general information purposes only. The information may be provided by either EduDuck.com or by a third party user of this site who has created a course or other learning materials. While we endeavour to keep the information up to date and correct, we make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability or availability with respect to the website or the information, products, services, or related graphics contained on the website for any purpose. Any reliance you place on such information is therefore strictly at your own risk.</li>
<li>In no event will we be liable for any loss or damage including without limitation, indirect or consequential loss or damage, or any loss or damage whatsoever arising from loss of data or profits arising out of, or in connection with, the use of this website.</li>
<li>Through this website you are able to link to other websites which are not under the control of EduDuck.com. We have no control over the nature, content and availability of those sites. The inclusion of any links does not necessarily imply a recommendation or endorse the views expressed within them.</li>
<li>Every effort is made to keep the website up and running smoothly. However, EduDuck.com takes no responsibility for, and will not be liable for, the website being unavailable due to technical issues beyond our control.</li>
</ol>
{% endblock content %}

terms/templates/terms/terms_enrolling.html
{% extends "terms/terms_base.html" %}

{% block breadcrumb %}
<p id='id_breadcrumb'>
    <a href="{% url 'terms:terms_index' %}">T&amp;C</a> &gt; 
    <a href="{% url 'terms:terms_enrolling' %}">Enrolling</a>
</p>
{% endblock breadcrumb %}

{% block contentheading %}
    <h2 id='id_page_title'>Terms and Conditions for Enrolling on a Course</h2>
{% endblock contentheading %}

{% block content %}
<p>We hope that you will enjoy enrolling on the courses we host on EduDuck.com.</p>
<p>In addition to the <a href="{% url 'terms:terms_browsing' %}">basic terms and conditions</a>, the following additional terms will apply should you choose to enrol on a course.</p>
<ol>
<li>Courses hosted on EduDuck.com may be produced and maintained by EduDuck.com directly or by third party users of the site.</li>
<li>Whilst we require course authors to produce courses of a good standard, you understand that course authors will necessarily have the ability to publish and edit material directly and without the approval of EduDuck.com. Thus there may be errors, omissions, offensive or misleading information. You are responsible for ensuring that information presented meets your needs, however if you identify errors, omissions, offensive or misleading information we would kindly request that you <a href="{% url 'support' %}">report it</a>. EduDuck.com will then check your report and take whatever action it deems necessary. This may result in deletion of material and suspension of accounts of users creating offensive material.</li>
<li>If completing any assessment or homework assignments as part of a course, you undertake that any work you submit will be your own.</li>
<li>If you have purchased access to a course, you can expect that the course will remain active on our system for at least 6 months. Beyond the 6 month timeframe, you accept that we may retire older courses from active availability in order to develop EduDuck.com's software platform and to keep the selection of courses relevant and up-to-date.</li>
<li>If a course is to be retired from active availability, we would aim to provide a summary and static record of your progress on that course, accessible via <a href="{% url 'profile' %}">your profile.</a></li>
<li>In the case where EduDuck.com might agree to refund any payment you have made for a course, the maximum refund you are entitled to shall not exceed the total of payments made for that particular course.</li>
<li>No refund can be paid after 7 days or after you have accessed a reasonable fraction of the course you have paid for.</li>
<li>EduDuck.com aims to be a polite and respectful shared learning environment. Disruptive or abusive behaviour will not be tolerated and any account used in a negative manner will probably be locked or deleted, resulting in the loss of any paid enrolment fees.</li>
<li>No course fee refunds will be available to users who engage in disruptive, abusive or hateful behaviour and have their accounts suspended as a result of this behaviour.</li>
<li>Users should protect their own safety and not give away sensitive personal or location information to other users that they do not know.</li>
<li>Any account suspension for reasons of abusive, disruptive or hateful behaviour shall be decided by EduDuck.com and may occur without notice to any user engaging in such behaviour. If such behaviour has occurred at a lower level EduDuck.com may attempt to contact the user and ask them to remove any offensive material.</li>
</ol>
{% endblock content %}

terms/templates/terms/terms_index.html
{% extends "terms/terms_base.html" %}

{% block breadcrumb %}
<p id='id_breadcrumb'>
    <a href="#">T&amp;C</a> 
</p>
{% endblock breadcrumb %}

{% block contentheading %}
    <h2 id='id_page_title'>Terms and Conditions</h2>
{% endblock contentheading %}

{% block content %}
    <p>Please check the following documents for our terms and conditions and usage disclaimer</p>
    <p>Assuming you are happy with the terms, you can <a id='id_accept_terms' href="{% url 'profile_edit' %}">accept them on your profile page.</a></p>
    <ol id='id_terms_menu'>
        <li><a href="{% url 'terms:terms_privacy' %}">Privacy policy</a></li>
        <li><a href="{% url 'terms:terms_browsing' %}">Browsing EduDuck.com</a></li>
        <li><a href="{% url 'terms:terms_enrolling' %}">Enrolling on a course</a></li>
        <li><a href="{% url 'terms:terms_creating' %}">Creating content</a></li>
        <li><a href="{% url 'terms:terms_disclaimer' %}">Website disclaimer</a></li>
    </ol>
    <p>(These terms and conditions are based up those found on the <a href='https://www.nibusinessinfo.co.uk/content/sample-it-policies-disclaimers-and-notices'>sample IT policies and disclaimers notices on the NIBusiness.co.uk website.</a>)</p>
{% endblock content %}

terms/templates/terms/terms_privacy.html
{% extends "terms/terms_base.html" %}

{% block breadcrumb %}
<p id='id_breadcrumb'>
    <a href="{% url 'terms:terms_index' %}">T&amp;C</a> &gt; 
    <a href="{% url 'terms:terms_privacy' %}">Privacy</a>
</p>
{% endblock breadcrumb %}

{% block contentheading %}
    <h2 id='id_page_title'>Privacy and Data Protection</h2>
{% endblock contentheading %}

{% block content %}
<p>This privacy policy sets out how EduDuck.com uses and protects any information that you give us when you use this website.</p>
<p>EduDuck.com is committed to ensuring that your privacy is protected. Should we ask you to provide certain information by which you can be identified when using this website, then you can be assured that it will only be used in accordance with this privacy statement.</p>
<p>EduDuck.com may change this policy from time to time by updating this page. You should check this page from time to time to ensure that you are happy with any changes. This policy is effective from November 2015.</p>
<h4>What we collect</h4>
<p>We may collect the following information:
<ol>
    <li>your name</li>
    <li>your preferred timezone</li>
    <li>contact information including email address</li>
    <li>third party authentication data, e.g. Facebook, depending on how you log in to EduDuck.com</li>
    <li>a link to your personal webpage (optional)</li>
    <li>a description of yourself (optional)</li>
    <li>demographic information such as postcode, preferences and interests (optional)</li>
    <li>other information relevant to customer surveys and/or offers</li>
    <li>your enrolment on courses hosted on EduDuck.com</li>
    <li>access datestamps as you work through course materials.</li>
    <li>your responses to any assessment tasks as part of a course.</li>
</ol>
</p>

<h4>Something we don't collect</h4>
<ol>
    <li>We don't collect credit or debit card information. These data are processed by third party payment processors (as of November 2015, by Stripe.com)</li>
</ol>

<h4>What we do with the information we gather</h4>
<p>We require this information to understand your needs and to provide you with a better service, and in particular for the following reasons:
<ul>
    <li>Internal record keeping.</li>
    <li>Logging and detection of suspicious activity.</li>
    <li>Improving our products and services.</li>
    <li>Contacting you with regard to any problems or issues concerning courses you are studying or have created.</li>
    <li>We may periodically send promotional emails about new products, special offers or other information which we think you may find interesting using the email address which you have provided.</li>
    <li>From time to time, we may also use your information to email you for market research purposes. We may use the information to customise the website according to your interests.</li>
</ul>
</p>

<h4>Security</h4>
<p>
We are committed to ensuring that your information is secure. In order to prevent unauthorised access or disclosure, we have put in place suitable arrangements to safeguard and secure the information we collect online.</p>

<h4>How we use cookies</h4>
<p>A cookie is a small file which asks permission to be placed on your computer's hard drive. Once you agree, the file is added and the cookie helps analyse web traffic or lets you know when you visit a particular site. Cookies allow web applications to respond to you as an individual. The web application can tailor its operations to your needs, likes and dislikes by gathering and remembering information about your preferences.</p>
<p>We use traffic log cookies to identify which pages are being used. This helps us analyse data about webpage traffic and improve our website in order to tailor it to customer needs. We only use this information for statistical analysis purposes.</p>
<p>Overall, cookies help us provide you with a better website by enabling us to monitor which pages you find useful and which you do not. A cookie in no way gives us access to your computer or any information about you, other than the data you choose to share with us.</p>
<p>You can choose to accept or decline cookies. Most web browsers automatically accept cookies, but you can usually modify your browser setting to decline cookies if you prefer. This may prevent you from taking full advantage of the website.</p>

<h4>Links to other websites</h4>
<p>Our website is likely to contain links to other websites of interest. However, once you have used these links to leave our site, you should note that we do not have any control over that other website. Therefore, we cannot be responsible for the protection and privacy of any information which you provide whilst visiting such sites and such sites are not governed by this privacy statement. You should exercise caution and look at the privacy statement applicable to the website in question.</p>

<h4>Controlling your personal information</h4>
<p>You may choose to restrict the collection or use of your personal information in the following ways:
<ol>
<li>whenever you are asked to fill in a form on the website, look for the box that you can click to indicate that you do not want the information to be used by anybody for direct marketing purposes</li>
<li>if you have previously agreed to us using your personal information for direct marketing purposes, you may change your mind at any time by emailing us at admin@eduduck.com</li>
</ol>
</p>
<p>We will not sell, distribute or lease your personal information to third parties unless we have your permission or are required by law to do so. We may use your personal information to send you promotional information about third parties which we think you may find interesting if you tell us that you wish this to happen.
<p>
You may request details of personal information which we hold about you under the Data Protection Act 1998. A small fee will be payable. If you would like a copy of the information held on you please email admin@eduduck.com.
</p>
<p>If you believe that any information we are holding on you is incorrect or incomplete, please email us as soon as possible at the previously noted address. We will promptly correct any information found to be incorrect.</p>
{% endblock content %}