EduDuck/urls.py
#EduDuck/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles import views as static_views
from django.views.generic import TemplateView

import attachment.urls
import checkout.urls
import courses.urls
import homepage.views
import interaction.urls
import lesson.urls
import outcome.urls
import profile.urls
import support.urls
import terms.urls

urlpatterns =  [
    url(r'^$', homepage.views.home, name='homepage'),
#    url(r'^search/', include('haystack.urls')),
    url(r'^about/$', TemplateView.as_view(template_name = 'about.html')),
    url(r'^priced_items/', include(checkout.urls, namespace='checkout')),
    url(r'^support/', include(support.urls)),
    url(r'^terms/', include(terms.urls, namespace='terms')),
    url(r'^lesson/(?P<lesson_id>\d+)/lint/', include(outcome.urls)),
    url(r'^courses/', include(courses.urls)),
    url(r'^interaction/', include(interaction.urls)),
    url(r'^accounts/profile/', include(profile.urls)),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^attachment/', include(attachment.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

courses/urls.py
#courses/urls.py
from django.conf.urls import include, url

from . import views
import lesson.urls

urlpatterns = [
    url(r'^$', views.index, name='course_index'),
    url(r'^(?P<course_id>\d+)/edit/$', views.edit, name='course_edit'),
    url(r'^(?P<course_id>\d+)/publish/$', views.publish, name='course_publish'),
    url(r'^(?P<course_id>\d+)/enrol/$', views.enrol, name='course_enrol'),
    url(r'^(?P<course_id>\d+)/$', views.detail, name='course_detail'),
    url(r'^create/$', views.create, name='course_create'),
    url(r'^(?P<course_id>\d+)/lesson/', include(lesson.urls)),
]

lesson/urls.py
#lesson/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^(?P<lesson_id>\d+)/$', views.visit, name='lesson_visit'),
    url(r'^(?P<lesson_id>\d+)/edit/$', views.edit, name='lesson_edit')
]

terms/urls.py
#terms/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from .import views

urlpatterns = [
    url(
        r'^$', 
        TemplateView.as_view(template_name='terms/terms_index.html'),
        name = 'terms_index'
    ),
    url(
        r'disclaimer/$',
        TemplateView.as_view(template_name='terms/terms_disclaimer.html'),
        name = 'terms_disclaimer'
    ),
    url(
        r'privacy/$',
        TemplateView.as_view(template_name='terms/terms_privacy.html'),
        name = 'terms_privacy'
    ),
    url(
        r'browsing/$', 
        TemplateView.as_view(template_name='terms/terms_browsing.html'),
        name = 'terms_browsing'
    ),
    url(
        r'enrolling/$', 
        TemplateView.as_view(template_name='terms/terms_enrolling.html'),
        name = 'terms_enrolling'
    ),
    url(
        r'creating/$',
        TemplateView.as_view(template_name='terms/terms_creating.html'),
        name = 'terms_creating'
    ),
]

courses/models.py
from django.core.urlresolvers import reverse
from django.db import models
from django.http import Http404
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from checkout.models import PricedItem
from profile.models import Profile 


class Course(models.Model):
    """A self contained course of study.
    
    Attributes:
        code         Optional. Course code for human consumption
        name         Human readable name of course
        abstract     Summary paragraph outlining course
        published    Boolean. True if published. Default False
        organiser    Foreign key: user organising course
        instructor   Foreign key: user providing instruction 
    """

    class Meta:
        permissions = (
            ("study_course", "User can enrol and study this course"),
        )
    
    code = models.CharField(
        max_length=10,
        help_text="optional course code for author's reference",
        blank=True
    )
    name = models.CharField(
        max_length=20,
        help_text="human readable short name of the course"
    )
    abstract = models.TextField(
        help_text="summary of the course in a couple of paragraphs"
    )
    published = models.BooleanField(
        default = False,
        blank = False,
        null = False
    )
    organiser = models.ForeignKey(
        User,
        related_name="courses_organised_set",
        help_text="This user is organising the course"
    )
    instructor = models.ForeignKey(
        User,
        related_name="courses_instructed_set",
        help_text="This user is providing the instruction"
    )

    def __init__(self, *args, **kwargs):
        super (Course, self).__init__(*args, **kwargs)

        #When adding a new instance (e.g. in admin), their will be no 
        #datamembers, so only check existing instances eg. from db load.
        if self.pk != None:
            self._checkrep()

    def __unicode__(self):
        return self.name
    
    def get_absolute_url(self):
        assert self.id >=1
        return reverse(u"courses.views.detail", kwargs= {'course_id': self.id})

    def save(self, *args, **kwargs):
        super(Course, self).save(*args, **kwargs)
        course_type = ContentType.objects.get_for_model(Course)
        (pitem, created) = PricedItem.objects.get_or_create(
            content_type_id = course_type.pk,
            object_id=self.pk
        )
        self._checkrep()
        
    def _checkrep(self):
        assert self.name
        assert self.organiser
        assert self.instructor
        course_type = ContentType.objects.get_for_model(Course)
        pitem = PricedItem.objects.get_or_create(
            content_type_id = course_type.pk,
            object_id=self.pk
        )

lesson/models.py
from django.core.urlresolvers import reverse
from django.db import models
from courses.models import Course

import logging
logger = logging.getLogger(__name__)

# Create your models here.

class Lesson(models.Model):
    """A digestible chunk of learning material within a course.
    
    Attributes:
    name        Human readable full lesson name
    course      ForeignKey - course to which lesson belongs
    abstract    short text description of the lesson
    
    """
    
    name = models.CharField(max_length=200, verbose_name='lesson title')
    course = models.ForeignKey(Course, 
                               help_text="course to which this "
                               "lesson belongs")
    abstract = models.TextField(help_text="summary of the lesson "
                                "in a couple of paragraphs")
    
    def _checkrep(self):
        if not self.name:
            logger.warn("Lesson {0} name is empty".format(self.pk))
            return False
        assert self.course
        return True

    def get_next(self):
        """Return the next lesson in the course"""
        assert self.course
        assert self.id
        next = Lesson.objects.filter(course=self.course).filter(id__gt=self.id)
        if next:
            return next[0]
        return False
    
    def get_prev(self):
        """Return the previous lesson in the course"""
        assert self.course
        assert self.id
        prev = Lesson.objects.filter(course=self.course).filter(id__lt=self.id).order_by('-id')
        if prev:
            return prev[0]
        return False
    
    def __init__(self, *args, **kwargs):
        """checkrep on instantiation"""
        super (Lesson, self).__init__(*args, **kwargs)
        #When adding a new instance (e.g. in admin), their will be no 
        #datamembers, so only check existing instances eg. from db load.
        if self.pk != None:
            self._checkrep()
    
    def __unicode__(self):
        return self.name
    
    def get_absolute_url(self):
        assert self.course
        assert self.id
        return reverse(u"lesson_visit", kwargs = { 
            'course_id': self.course.id,
            'lesson_id': self.id })
            

video/models.py
from django.core.exceptions import ValidationError
from django.db import models
from courses.models import Course
from lesson.models import Lesson
from video.utils import force_https, validate_youtube_url

from core.eduduck_exceptions import CheckRepError

import logging
logger = logging.getLogger(__name__)

class Video(models.Model):
    """ URLs and various meta data
    
    Attributes:
        name        Text name of the video for human consumption
        url         Yep.
        lesson      FK to lesson } one of these two must be non-null
        course      FK to course } one of these two must be non-null
        
    """
    
    #TODO: use YouTube / Vimeo APIs to pull video meta data such as title, tags    
    name = models.CharField(max_length=200)
    url = models.URLField(validators=[validate_youtube_url])
    lesson = models.ForeignKey(Lesson, blank=True, null=True)
    course = models.ForeignKey(Course, blank=True, null=True)
    
    def __str__(self):
        return "Video: {0}".format(self.name)

    def __unicode__(self):
        return self.name
    
    def get_absolute_url(self):
        return self.url
    
    def _checkrep(self):
        if self.name == "":
            logger.warning("Video {0} lacks name".format(self.id))
            return False
        if self.url == "":
            logger.warning("Video {0} lacks url".format(self.id))
            return False
        # Convert any http:// protocols to https://
        if self.url[:7] == "http://":
            self.url = force_https(self.url)
            logger.info("Rewriting https protocol on video {0}".format(self.id))
            self.save()

        # At least one of these should not be zero:
        if not (self.course or self.lesson): 
            logger.error("Orphaned video")
            raise CheckRepError("Video has no FK to course or lesson")
        return True
    
    def __init__(self, *args, **kwargs):
        """Run _checkrep on instantiation"""
        super(Video, self).__init__(*args, **kwargs)
        
        # Convert any http:// protocols to https://
        if self.url[:7] == "http://":
            self.url = force_https(self.url)

        #When adding a new instance (e.g. in admin), their will be no 
        #datamembers, so only check existing instances eg. from db load.
        if self.pk != None:
            self._checkrep()
        
    def save(self, *args, **kwargs):
        if (self.lesson == None and self.course == None):
            logger.error("Orphaned video, save failed")
            raise CheckRepError("Orphaned video: no course or lesson")
        if (self.name == '' or self.url == ''): 
            logger.warning("Video lacks name or url")
            raise ValidationError
        
        super(Video, self).save(*args, **kwargs)
        

courses/forms.py
# Course forms
from django import forms
from courses.models import Course

COURSE_NAME_FIELD_REQUIRED_ERROR = "A course must have a short title"
COURSE_ABSTRACT_FIELD_REQUIRED_ERROR = "You must provide an abstract"\
    " (brief description)"

class CourseNameForm(forms.Form):
    """ A brief form, just course name and submit """
    course_short_name = forms.CharField(
        widget = forms.fields.TextInput(attrs={
            'placeholder': 'A short name for the course',
            'id': 'id_course_name',
        }),
    )

class CourseFullForm(forms.models.ModelForm):
    """ A fully featured form to create courses """
    class Meta:
        model = Course
        fields = ('code', 'name', 'abstract')
        error_messages = {
            'name': {'required': COURSE_NAME_FIELD_REQUIRED_ERROR},
            'abstract': {'required': COURSE_ABSTRACT_FIELD_REQUIRED_ERROR},
        }

lesson/forms.py
# lessons/forms.py

from django import forms
from lesson.models import Lesson

LESSON_NAME_FIELD_REQUIRED_ERROR = "A lesson must have a short title"
LESSON_ABSTRACT_FIELD_REQUIRED_ERROR = "A lesson must have a short abstract"

class LessonEditForm(forms.ModelForm):
    """A form to edit lessons"""
    class Meta:
        model = Lesson
        fields = ['name', 'course', 'abstract']
        error_messages = {
            'name': {'required':LESSON_NAME_FIELD_REQUIRED_ERROR},
            'abstract': {'required': LESSON_ABSTRACT_FIELD_REQUIRED_ERROR},
        }

    def __init__(self, *args, **kwargs):
        super(LessonEditForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['id'] = 'id_lesson_title'

checkout/views.py
from django.core.exceptions import PermissionDenied
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.utils.decorators import method_decorator
from django.shortcuts import get_object_or_404, render
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)
from checkout.models import Payment, PricedItem

class SuperuserRequiredMixin(object):
    @method_decorator(user_passes_test(
        lambda u: u.is_superuser, 
        login_url='/', 
        redirect_field_name=None
    ))
    def dispatch(self, *args, **kwargs):
        return super(SuperuserRequiredMixin, self).dispatch(*args, **kwargs)

class LoginRequiredMixin(object):
    @method_decorator(login_required())
    def dispatch(self, *args, **kwargs):
        return super(LoginRequiredMixin, self).dispatch(*args, **kwargs)

class PricedItemList(SuperuserRequiredMixin, ListView):
    model = PricedItem

class PricedItemCreate(SuperuserRequiredMixin, CreateView):
    model = PricedItem
    fields = ['content_type', 'object_id', 'fee_value', 'currency', 'tax_rate', 'notes']
    success_url = '/priced_items/'
    template_name_suffix = '_create_form'
    
    def form_valid(self, form):
        #mess around with form instance values here?
        #form.instance.currency=PricedItem.GBP
        return super(PricedItemCreate, self).form_valid(form)

class PricedItemUpdate(SuperuserRequiredMixin, UpdateView):
    model = PricedItem
    fields = ['content_type', 'object_id', 'fee_value', 'currency', 'tax_rate', 'notes']
    success_url = '/priced_items/' 
    template_name_suffix = '_update_form'

class PricedItemDelete(SuperuserRequiredMixin, DeleteView):
    model = PricedItem
    success_url = '/priced_items/'

class PricedItemDetail(LoginRequiredMixin, DetailView):
    model = PricedItem

class PaymentList(SuperuserRequiredMixin, ListView):
    model = Payment

class PaymentList_forUser(LoginRequiredMixin, ListView):
    def get_queryset(self):
        self.paying_user = get_object_or_404(User, id=self.request.user.id) 

    template_name = 'checkout/payment_for_user.html'

def payment_detail(request, payment_id):
    payment = get_object_or_404(Payment, pk=payment_id)
    if request.user.is_authenticated():
        if payment.paying_user == request.user:
            context_data = { 
                'object':   payment,
            }
            template = 'checkout/payment_detail.html'
            return render(request, template, context_data)
        else:
            raise PermissionDenied
    else:
        return HttpResponseRedirect('/login/') 

templates/courses/base_course.html
{% extends "base.html" %}
{% load staticfiles %}

templates/courses/course_detail.html
{% extends "courses/base_course.html" %}
{% load cycle from future %}
{% load staticfiles %}
{% load tz %}
{% load markdown_deux_tags %}
{% block extra_script %}
    <script src="{% static 'common.js' %}" ></script>
{% endblock extra_script %}
{% block menu_override %}
<li class='menu-item-divided'><a href="#">{{ course.name }}</a></li>
<li class='menu_subsection'><a href="#id_resource_videos">Intro Videos</a></li>
<li class='menu_subsection'><a href="#id_resource_lessons">Lessons</a></li>
<li class='menu_subsection'><a href="#id_resource_assessments">Assessments</a></li>
<li class='menu_subsection'><a href="#id_resource_study">Study Group</a></li>
<li class='menu_subsection'><a href="#id_resource_attachments">Course Docs</a></li>
<li class='menu_subsection'><a href="#id_resource_progress">Progress</a></li>
{% endblock menu_override %}

{% block breadcrumb %}
<p id='id_breadcrumb'>
    <a href="{% url 'courses.views.index' %}">All Courses</a> &gt; 
    <a href="#">{{ course.name }} Home</a>
</p>
{% endblock breadcrumb %}
    
{% block contentheading %}
<h2 id='id_course_title'>{{ course.name }}</h2>
{% endblock contentheading %}

{% block content %}    
<div id='id_course_intro_area' class='pure-g-r'>
    <div class='pure-u-4-5'>
        <h3>
            {% if course.code %}{{ course.code }}
            {% else %}{{ course.pk }}
            {% endif %}: {{ course.name }} Course Homepage</h3>
    </div>
    <div class='pure-u-1-5'>
        {% if status == "auth_bar_enrol" %}
            {% if user_can_edit %}
                <a  href = "{% url 'course_edit' course_id=course.id %}"
                    id='id_edit_course'
                    class='pure-button pure-button-primary'>
                        Edit Course
                </a>
                {% if course.published %}
                    <p id='id_published_message'>Course Status: Published</p>
                {% else %}
                    <a  href = "{% url 'course_publish' course_id=course.id %}"
                        id='id_publish_button' 
                        class='pure-button pure-button-primary'>
                        Publish Course
                    </a>
                {% endif %}
            {% endif %}
            <p>You are involved in running this course.</p>
        {% elif status == "auth_not_enrolled" %}
            {% if fee_value_cents == 0 %}
                <form   class='pure-form' 
                        action='' 
                        method='post'>
                    {% csrf_token %}
                    <button id='id_enrol_button' 
                            class='pure-button pure-button-primary' 
                            type='submit' 
                            name='course_enrol'>
                        Enrol &#163;Free
                    </button>
                </form>
            {% else %}
                <form   class='pure-form' 
                        action='' 
                        method='post'>
                    {% csrf_token %}
                    <button id='id_enrol_button' 
                            class='pure-button pure-button-primary' 
                            type='submit' 
                            name='course_enrol'>
                        Enrol &#163;{{ fee_value }}
                    </button>
                    {% include 'checkout/checkout_overlay.html' %}
                </form>
            {% endif %}
        {% elif status == "auth_enrolled" %}
            <p>You're enrolled on this course</p>
        {% else %}
            <form   class='pure-form' 
                    action='/accounts/register/' 
                    method='post'>
                {% csrf_token %}
                <button id='id_signup_button' 
                        class='pure-button pure-button-primary' 
                        type='submit' 
                        name='signup'>
                    Sign Up!
                </button>
            </form>
        {% endif %}
    </div>
    
    <div id='id_abstract' class='pure-u-1-2'>
        <p>Hi, and welcome to {{ course.name }}</p>
        <p>{{ course.abstract|markdown }}</p>
        <p>Course organiser <a href="{{ course.organiser.profile.get_profile_url}}">{% firstof course.organiser.get_full_name course.organiser.username %}</a></p>
        <p>Course instructor <a href="{{course.instructor.profile.get_profile_url}}">{% firstof course.instructor.get_full_name course.instructor %}</a></p>
    </div>
    <div id='id_intro_video' class='pure-u-1-2'>
        {% for v in course.video_set.all|slice:":1" %}
        {{v.name}}<br>
        <iframe width="201" height="113" src="{{v.url}}" frameborder="0" allowfullscreen></iframe>
        {% empty %}
                <p>There are no intro videos for this course</p>
                <iframe width="201" height="113" src="//www.youtube.com/embed/fkm00ZffzNM" frameborder="0" allowfullscreen></iframe>
        {% endfor %}
        <br />            
    </div>
</div><!-- id_course_intro_area-->

<div id='id_resource_area' class='pure-g-r'>
    <div class='pure-u-1-3' id='id_resource_lessons'>
        <h3>Lessons</h3>
        <p>There 
        {{course.lesson_set.count|pluralize:"is,are"}} {{course.lesson_set.count}} 
        lesson{{course.lesson_set.count|pluralize:",s"}} in this course.</p>
        <ul class='pure-paginator'>
            {% for lesson in course.lesson_set.all %}
            <li><a class='pure-button' 
                href='{{ lesson.get_absolute_url }}'
                title='{{ lesson.name}}'
                id='id_lesson{{ forloop.counter }}'>{{ forloop.counter }}
            </a></li>
            {% endfor %}
        </ul>

        {% regroup course.lesson_set.all by lesson.code as lesson_list %}
        {% for lesson in course.lesson_set.all %}
            <h4 class='shadable'>
                <a href='{{ lesson.get_absolute_url }}'>{{ lesson.name }}</a>
            </h4>
            <article class="abstract">
                <p>{{ lesson.abstract | markdown}} 
                <a href='{{ lesson.get_absolute_url }}'>Go to lesson</a>
                </p>
            </article>
        {% empty %}
            <h4>No Lessons</h4>
            <article class="abstract">
            <p>{% firstof course.organiser.get_full_name course.organiser.username %} hasn&#39;t added any lessons yet!</p>
            </article>
        {% endfor %}
        
    </div>
    <div class='pure-u-1-3' id='id_resource_assessments'>
        <h3>Assessments</h3>
    </div>
    <div class='pure-u-1-3' id='id_resource_study'>
        <h3>Study Group & Course News</h3>
        <p>Combined news feed, possibly user configurable forum RSS, 
        twitter, G+, Facebook etc. (Students often set up own groups</p>
    </div>
    
    <div class='pure-u-1-3' id='id_resource_attachments'>
        <h3>Documents Attached</h3>
        <ol id='id_attachment_list'>
        {% for a in attachments %}
        <li>
            {{ a.1.pk}}&nbsp;[
                {% if a.0 %}
                Downloaded
                {% else %}
                Not Downloaded
                {% endif %}]&nbsp;   
            <a href='{{ a.1.get_loggable_url }}'>{{ a.1.name }}</a>
            : {{ a.1.attachment.size }} bytes, {{ a.1.desc|markdown }}
            <a href='{{ a.1.get_metadata_url }}'>(View MetaData here)</a>
        </li>
        {% endfor %}
        </ol>  
    </div>

    <div class='pure-u-1-3' id='id_resource_videos'>
        <h3>Intro Videos</h3>
        {% for v in course.video_set.all %}
            {{ v.name }}
            <iframe width="280" height="158" src='{{ v.url }}' 
            frameborder="0" allowfullscreen></iframe>
        {% empty %}
            <p>There are no introductory videos for this course</p>
        {% endfor %}
    </div>
    <div class='pure-u-1-3' id='id_resource_progress'>
        {% if status == "auth_enrolled" %}
        <h3>Your Progress</h3>
        <p>Current status: {{ uc.get_status }}</p>
        {% if uc.get_status == 'active' %}
        <form action='' method='post'>{% csrf_token %}
            <input type="submit" name="course_complete" value="Complete"
            title="Mark the course as complete">
            <input type="submit" name="course_withdraw" value="Withdraw"
            title="Withdraw from the course">
            </form>  
            {% else %}
            <form action='' method='post'>{% csrf_token %}
            <input type="submit" name="course_reopen" value="Re-open">
            </form>  
            {% endif %}
            <ol>{% for event in history %}
            <li>{{ event.1 }} on {{ event.0|localtime }}</li>
            {% endfor %}</ol>
            <h4>Lessons Visited</h4>
            <table border='1'>
            <thead>
            <tr><th>Status</th><th>Lesson</th></tr>
            </thead>
            <tbody>
            {% for lesson, ul in lessons %}<tr><td>
            {% if ul.completed %}Completed
            {% elif ul.visited %}Visited
            {% endif %}
            </td><td>{{ lesson.name }}</td></tr>
            {% endfor %}
            </tbody>
            </table>
        {% elif status == "auth_not_enrolled" %}
            <h3>Enrol Here</h3>
            <div id='id_enrol_area'>
                {% if fee_value_cents == 0 %}
                    <form   class='pure-form' 
                            action='' 
                            method='post'>
                        {% csrf_token %}
                        <button id='id_enrol_button2' 
                                class='pure-button pure-button-primary' 
                                type='submit' 
                                name='course_enrol'>
                            Enrol &#163;Free
                        </button>
                    </form>
                {% else %}
                    <form   class='pure-form' 
                            action='' 
                            method='post'>
                        {% csrf_token %}
                        <button id='id_enrol_button2' 
                                class='pure-button pure-button-primary' 
                                type='submit' 
                                name='course_enrol'>
                            Enrol &#163;{{ fee_value }}
                        </button>
                        {% include 'checkout/checkout_overlay.html' %}
                    </form>
                {% endif %}
            </div>
        {% elif status == "anon" %}
            <div id="id_signup_area">
            <h3>Sign Up Here</h3>
                <form   class='pure-form' 
                action='/accounts/register/' 
                method='post'>
                {% csrf_token %}
                <button id='id_signup_button2' 
                class='pure-button pure-button-primary' 
                type='submit' 
                name='signup'>
                Sign Up!
                </button>
            </div>
        {% elif status == "auth_bar_enrol" %}
            <h3>Edit Course</h3>
            {% if user_can_edit %}
                <a  href = "{% url 'course_edit' course_id=course.id %}"
                    id='id_edit_course'
                    class='pure-button pure-button-primary'>
                        Edit Course
                </a>
            {% endif %}
            <p>You are involved in running this course.</p>
        {% endif %}
    </div>
</div><!-- id_resource_area -->
{% endblock content %}

templates/courses/course_index.html
{% extends "courses/base_course.html" %}
{% load cycle from future %}
{% load staticfiles %}
{% load tz %}

{% block menu_override %}
{% endblock menu_override %}

{% block breadcrumb %}
<p id='id_breadcrumb'>
<a href="{% url 'courses.views.index' %}">All Courses</a>
</p>
{% endblock breadcrumb %}

{% block contentheading %}
<h2 id='id_page_title'>All Course Index</h2>
{% endblock contentheading %}

{% block content %}
<div class="content">
    <div id="id_course_selection" class="pure-g-r">
    {% for course in course_list %}
        <div class="random_course pure-u-{{ course.1 }}-24 
        {% cycle 'seg1' 'seg2' 'seg3' 'seg4' 'seg5' 'seg6' %}">
            <a href='{{ course.0.get_absolute_url }}' 
                id='id_{{course.0.name}}_course'>{{ course.0.name }}</a>
        </div>
    {% empty %}
        <div class="random_course pure-u-24-24">
           <p>No courses?</p>
        </div>
    {% endfor %}
    </div>
    <div id='id_course_personal_area' class='pure-g-r'>
        <div class='pure-u-1-3'>
            <h2>Courses You Enrolled On</h3>
            <p>Not implemented yet</p>
        </div>
        <div class='pure-u-1-3'>
            <h2>Courses You Instruct or Organise</h2>
            <p>Not implemented yet</p>
        </div>
        <div class='pure-u-1-3'>
            <h2>Courses of Interest to you</h2>
            <p>You have flagged these up as maybe interesting to do later.</p>
            <p>Not implemented yet</p>
        </div>
    </div>
</div>
{% endblock %}

templates/courses/index.html
{% extends "base.html" %}

{% block banner %}
    <h1>EduDuck Course Area</h1>
{% endblock %}

{% block content %}
    <h2>Welcome to the Full Course List</h2>
    <p>EduDuck is currently hosting {{ course_count }} 
    course{{ course_count|pluralize:",s"}}.</p>
    
    <ul>
        {% for course in course_list %}
        <li>{{ course.course_code }} 
        <a href='{{ course.get_absolute_url }}'>{{ course.course_name }}</a> 
        ({{ course.lesson_set.count }} 
        lesson{{ course.lesson_set.count|pluralize:",s"}}). 
        Level {{ course.course_level }}, {{ course.course_credits }}
        point{{course.course_credits|pluralize:",s"}}.
        Contact {{ course.course_organiser }}</li>
        {% empty %}
        <li>There are no courses yet!</li>
        {% endfor %}
    </ul>
{% endblock content%}

templates/courses/single.html
{% extends "base.html" %}

{% block banner %}
    <h1>Single Course Detail View</h1>
{% endblock %}

{% block content %}
    <h2>Course: {{course.course_name}}</h2>
    <h3>Course Information & Introduction</h3>
    <ol>
    {% for v in course.video_set.all %}
        <li>{{ v.video_code}} {{v.video_name}}: {{v.url}}</li>
        <iframe width="560" height="315" src='{{ v.url }}' 
        frameborder="0" allowfullscreen></iframe>
    {% empty %}
        <li>No videos on course page</li>
    {% endfor %}
    </ol>

    <ol>
    {% for a in course.attachment_set.all %}
        <li>{{ a.att_code}} 
            <a href='{{a.attachment.url}}'>{{a.att_name}}</a>
            : {{a.attachment.size}} bytes, {{a.att_desc}}
        </li>
    {% empty %}
        <li>No attachments to course introduction page</li>
    {% endfor %}
    </ol>    

    <h3>Lessons</h3>
    <p>There 
    {{course.lesson_set|pluralize:"is,are"}} {{course.lesson_set.count}} 
    lesson{{course.lesson_set.count|pluralize:",s"}} in this course.</p>

    {% regroup course.lesson_set.all by lesson.lesson_code as lesson_list %}
    <ol>
        {% for lesson in course.lesson_set.all %}
            <li>
                {{ lesson.lesson_code}}, 
                <a href='{{ lesson.get_absolute_url }}'>
                    {{ lesson.lesson_name }}
                </a>
                <em>&nbsp;&nbsp;{{ lesson.abstract}}</em>
                {% if lesson.quiz_set.all %}
                    {% for quiz in lesson.quiz_set.all %}
                    <br />Quiz: <a href='/quiz_take/{{ quiz.id }}'>{{ quiz.quiz_title }}</a>
                    {% endfor %}
                {% endif %}
                <hr />
            </li>
        {% empty %}
            <li>No lessons in this course yet</li>
        {% endfor %}
    </ol>

{% endblock %}